import { defineTool } from '@flue/runtime';
import type { SlackThreadRef } from '@flue/slack';
import * as v from 'valibot';
import { getSlackConfig } from '../lib/config.ts';
import { asJson } from '../lib/json.ts';

const reportInput = v.object({
  riskLevel: v.pipe(v.picklist(['low', 'medium', 'high', 'critical']), v.description('Overall risk assessment')),
  summary: v.pipe(v.string(), v.description('One sentence summary of the event')),
  keyFindings: v.pipe(v.array(v.string()), v.description('Bullet list of the most important findings')),
  accessEvent: v.pipe(v.string(), v.description('Description of the triggering Access event')),
  gatewayActivity: v.pipe(v.string(), v.description('Notable Gateway DNS/HTTP activity around the event')),
  postureStatus: v.pipe(v.string(), v.description('Device posture check summary')),
  threatIntelHits: v.pipe(v.array(v.string()), v.description('Any threat intelligence matches found')),
  recommendedAction: v.pipe(v.string(), v.description('Recommended next step for the security team')),
});

type Report = v.InferOutput<typeof reportInput>;

const RISK_EMOJI: Record<Report['riskLevel'], string> = {
  low: '\u{1F7E2}',      // green
  medium: '\u{1F7E1}',   // yellow
  high: '\u{1F7E0}',     // orange
  critical: '\u{1F534}', // red
};

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/** Plain-text render — used as the Slack notification fallback and for run output. */
export function formatReport(r: Report): string {
  const bullets = (items: string[]) =>
    items.length ? items.map((i) => `  \u2022 ${i}`).join('\n') : '  (none)';
  return [
    `ZERO TRUST TRIAGE REPORT  \u2014  risk: ${r.riskLevel.toUpperCase()}`,
    `Summary: ${r.summary}`,
    '',
    'Key findings:',
    bullets(r.keyFindings),
    '',
    `Access event:     ${r.accessEvent}`,
    `Gateway activity: ${r.gatewayActivity}`,
    `Device posture:   ${r.postureStatus}`,
    '',
    'Threat intel hits:',
    bullets(r.threatIntelHits),
    '',
    `Recommended action: ${r.recommendedAction}`,
  ].join('\n');
}

/** Escape Slack mrkdwn control characters in interpolated content. */
function esc(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Slack Block Kit render — a structured, readable report card. */
export function buildBlocks(r: Report): unknown[] {
  const bullets = (items: string[]) =>
    items.length ? items.map((i) => `\u2022 ${esc(i)}`).join('\n') : '_(none)_';

  return [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: `${RISK_EMOJI[r.riskLevel]} Zero Trust Triage \u2014 ${r.riskLevel.toUpperCase()}`,
        emoji: true,
      },
    },
    { type: 'section', text: { type: 'mrkdwn', text: `*Summary*\n${esc(r.summary)}` } },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Access event*\n${esc(r.accessEvent)}` },
        { type: 'mrkdwn', text: `*Gateway activity*\n${esc(r.gatewayActivity)}` },
        { type: 'mrkdwn', text: `*Device posture*\n${esc(r.postureStatus)}` },
      ],
    },
    { type: 'section', text: { type: 'mrkdwn', text: `*Key findings*\n${bullets(r.keyFindings)}` } },
    { type: 'section', text: { type: 'mrkdwn', text: `*Threat intel hits*\n${bullets(r.threatIntelHits)}` } },
    { type: 'divider' },
    { type: 'section', text: { type: 'mrkdwn', text: `*Recommended action*\n${esc(r.recommendedAction)}` } },
    {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: 'Generated by zero-trust-investigator' }],
    },
  ];
}

// ---------------------------------------------------------------------------
// Slack delivery
// ---------------------------------------------------------------------------

type PostResult = { ok: true } | { ok: false; error: string };

async function postToSlack(dest: SlackThreadRef, r: Report): Promise<PostResult> {
  const { botToken } = getSlackConfig();
  if (!botToken) return { ok: false, error: 'SLACK_BOT_TOKEN not set' };

  let res: Response;
  try {
    res = await fetch('https://slack.com/api/chat.postMessage', {
      method: 'POST',
      headers: {
        authorization: `Bearer ${botToken}`,
        'content-type': 'application/json; charset=utf-8',
      },
      body: JSON.stringify({
        channel: dest.channelId,
        thread_ts: dest.threadTs,
        text: formatReport(r), // notification fallback + accessibility
        blocks: buildBlocks(r),
      }),
    });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  if (!res.ok) return { ok: false, error: `Slack HTTP ${res.status}` };
  const body = (await res.json().catch(() => ({}))) as { ok?: boolean; error?: string };
  if (body.ok === true) return { ok: true };
  return { ok: false, error: body.error ?? 'unknown Slack API error' };
}

/**
 * Build the triage-report tool. When `dest` (a Slack thread) is provided —
 * i.e. the investigation was triggered from Slack — the report is posted back
 * to that thread. Otherwise (e.g. a local `flue run`) it is rendered to the
 * run output so the investigate -> score -> report loop still completes.
 *
 * Delivery is never silently downgraded: if the investigation came from Slack
 * but posting fails, the tool returns `delivered: 'failed'` with the error so
 * the agent (and the analyst) know the report did not reach the thread. The
 * report is still written to run output as a last-resort fallback.
 */
export function createTriageReportTool(dest?: SlackThreadRef) {
  return defineTool({
    name: 'post_triage_report',
    description:
      'Post the completed Zero Trust triage report to the originating Slack thread, or to the run ' +
      'output when there is no Slack thread. Returns delivered: "slack" | "run-output" | "failed"; ' +
      'a "failed" result means the report could NOT be delivered to Slack and includes the error.',
    input: reportInput,
    // Posting to Slack is an external side effect. If the Worker is interrupted
    // after Slack accepts the message but before the tool result is recorded,
    // recovery replays the recorded step result instead of re-posting — so the
    // report is never double-delivered to the thread.
    durable: true,
    async run({ data, step, log }) {
      if (dest) {
        const result = await step.do('post-to-slack', () => postToSlack(dest, data));
        if (result.ok) {
          return asJson({ delivered: 'slack', riskLevel: data.riskLevel });
        }
        // Surface the failure through observability instead of pretending the
        // report was delivered. The full report rides back on the result so it
        // is not lost when Slack delivery fails.
        log.warn('Slack delivery failed; falling back to run output', {
          error: result.error,
          riskLevel: data.riskLevel,
        });
        return asJson({
          delivered: 'failed',
          riskLevel: data.riskLevel,
          error: result.error,
          report: formatReport(data),
        });
      }

      log.info('No Slack thread bound; triage report delivered to run output', {
        riskLevel: data.riskLevel,
      });
      return asJson({ delivered: 'run-output', riskLevel: data.riskLevel, report: formatReport(data) });
    },
  });
}
